PROJ_NAME=devguide

all:
	pdflatex ${PROJ_NAME}.tex
	pdflatex ${PROJ_NAME}.tex
	pdflatex ${PROJ_NAME}.tex

clean:
	-rm ${PROJ_NAME}.aux
	-rm ${PROJ_NAME}.log
	-rm ${PROJ_NAME}.pdf
	-rm ${PROJ_NAME}.toc
